spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:~/test1
    password: ''
  h2:
    console:
      enabled: true
      path: /h2
  application:
    name: produit-service
  jpa:
    hibernate:
      ddl-auto: create-drop
eureka:
   serviceUrl:
      defaulZone: http://discovery:8761/eureka-server/
server:
  port: '8083'
  
